### ISSUE TITLE
gpkg to geojson

### ISSUE THREAD

**Issue by jfoclpf** [ngageoint/geopackage-geojson-js#1]
How to fully convert a geoPackage file to a GeoJson (or extract everything from the geoPackage to GeoJson)?

**Comment by danielbarela** [comment]
```
async extract(geopackage: GeoPackage, tableName: string): Promise<any> {
    const geoJson = {
      type: 'FeatureCollection',
      features: [],
    };
    const iterator = geopackage.iterateGeoJSONFeatures(tableName);
    for (const feature of iterator) {
      geoJson.features.push(feature);
    }
    return Promise.resolve(geoJson);
  }
```

**Comment by jfoclpf** [comment]
I'm not that versed on GeoPackage files, but for that you need to know the `tableName` beforehand, right?

**Comment by danielbarela** [comment]
Yes, you would need to pass in the table name you want to extract.  You can read the table names from the GeoPackage with the API geopackage.getTables()

**Comment by danielbarela** [comment]
https://ngageoint.github.io/geopackage-js/classes/geopackage.html#gettables

**Comment by jfoclpf** [comment]
Thank you, can you provide me some documentation for the JS API? 

fixed ;)
thanks

**Comment by danielbarela** [comment]
The most current documentation is located here: https://ngageoint.github.io/geopackage-js/index.html

**Comment by jfoclpf** [comment]
thanks again, you should have that link in the main `readme.md` of this repo IMO, not easy to find _prima facie_
